language: csharp

mono:
  - 4.8.1
  - latest

matrix:
  allow_failures:
    - mono: latest
  
sudo: false  # use the new container-based Travis infrastructure

script: 
  - ./build.sh Default

branches:
  except:
    - gh-pages
