install:
  - cinst fake -pre
build_script:
  - ps: Fake.netcore.exe -v run build.fsx
#  - ps: .\build.cmd
test: off
artifacts:
  - path: build
    name: binaries
  - path: 'nuget\dotnetcore\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
    type: Zip