image: Visual Studio 2017
install:
  - cinst fake -pre
build_script:
# See https://stackoverflow.com/a/12866669/1269722
# Problem is that colors are lost
# Don't blame me but powershell is the bigest crap on earth
  - ps: |
      $pinfo = New-Object System.Diagnostics.ProcessStartInfo
      $pinfo.FileName = "fake.exe"
      $pinfo.WorkingDirectory = $pwd
      $pinfo.RedirectStandardError = $true
      $pinfo.RedirectStandardOutput = $false
      $pinfo.UseShellExecute = $false
      $pinfo.Arguments = '-v run build.fsx'
      $p = New-Object System.Diagnostics.Process
      $p.StartInfo = $pinfo
      Register-ObjectEvent -InputObject $p -EventName ErrorDataReceived -Action {
        $Global:test = $Event
        Write-Host $test.SourceEventArgs.Data -ForegroundColor red
      } | Out-Null
      $p.Start() | Out-Null
      $p.BeginErrorReadLine()
      $exited = $p.HasExited
      while ($exited -eq $false) { $p.Refresh(); $exited = $p.HasExited; [System.Threading.Thread]::Sleep(50) }
      $p.WaitForExit()
      if ($p.ExitCode -ne 0) {
        throw "fake failed with $LASTEXITCODE" 
      } else {
        Write-Host "Fake build finished sucessfully"
      }
#  - ps: .\build.cmd
on_failure:
  - appveyor PushArtifact FAKE.svclog
test: off
environment:
  PAKET_BOOTSTRAPPER_TRACE: true

artifacts:
  - path: 'nuget\dotnetcore\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\legacy\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
    type: Zip
